apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-pr-board-public
  annotations:
    github.com/project-slug: Developer-portal-Backstage/nom-du-repo
spec:
  type: service
  owner: group:default/frontend
  lifecycle: experimental
